print ("My name is Charlotte")
print ("My name is Emily")
print ("My name is Elyse")
print ("I was born in Abington, PA")
print ("I was born in New York")
print ("I was also born in New York")
print ("My favorite food is Pizza")
print ("My favorite type of Music is chill hits")
print ("My astrological sign is a Gemeni")
print ("My mothers maiden name is Kirsh")
