print ("My name is Charlotte")
print ("My name is Emily")
print ("My name is Elyse")
print ("I was born in Abington, PA")
print ("I was born in New York")
print ("I was also born in New York")
print("My favorite food is ice cream")
print("My favorite music is pop")
print ("My astrological sign is Taurus")
print ("My mother's maiden name is Bauman")
